import * as fs from "node:fs";
import * as path from "node:path";
import { spawnSync } from "node:child_process";
import { Command, Args } from "@oclif/core";
import { requireOrmFeatureDir, resolveOrmDriver, resolveOrmDriverName, resolveForjaDrivers, ormConfigContent } from "../../ormDriver";
import { writeEnvVars } from "../../envVars";

interface JsonObject {
  [key: string]: unknown;
}

export default class OrmSwitchDriverCommand extends Command {
  static description =
    "Switch the driver wired into features/orm/ — regenerates driver.js (and orm.config.js if the storage kind changes) so every model keeps working untouched. Does NOT migrate existing data between drivers.";

  static args = {
    name: Args.string({ required: true, description: "New driver name, e.g. 'postgres'" }),
  };

  async run(): Promise<void> {
    const { args } = await this.parse(OrmSwitchDriverCommand);
    const cwd = process.cwd();

    let ormFeatureDir: string;
    try {
      ormFeatureDir = requireOrmFeatureDir(cwd);
    } catch (err) {
      this.error((err as Error).message);
    }

    const forjaDrivers = resolveForjaDrivers();
    const newDriverName = args.name;
    const newDriver = forjaDrivers[newDriverName];
    if (!newDriver) {
      this.error(`Unknown driver "${newDriverName}" (available: ${Object.keys(forjaDrivers).join(", ")}).`);
    }

    const currentDriverName = resolveOrmDriverName(ormFeatureDir);
    const currentDriver = resolveOrmDriver(ormFeatureDir);

    if (currentDriverName === newDriverName) {
      this.error(`"${newDriverName}" is already the active driver.`);
    }

    const addonPackageJsonPath = require.resolve("@forjajs/orm/package.json");
    const templatesDir = path.join(path.dirname(addonPackageJsonPath), "templates");

    // Remove the old driver's adapter file, copy the new one in.
    fs.rmSync(path.join(ormFeatureDir, currentDriver.template), { force: true });
    fs.copyFileSync(path.join(templatesDir, newDriver.template), path.join(ormFeatureDir, newDriver.template));

    // Regenerate the stable indirection file — models never change.
    fs.writeFileSync(
      path.join(ormFeatureDir, "driver.js"),
      `// Regenerated by \`forja orm switch-driver ${newDriverName}\`.
// Models require() this file, never a driver's adapter file directly — that's
// what lets the active driver change without touching any model.
module.exports = require("./${newDriver.template}");
`,
    );

    // orm.config.js's shape depends on the driver's kind (path vs
    // connectionString) — only regenerate it if that actually changed, so a
    // hand-edited config (custom paths, env var names) isn't clobbered when
    // switching between two drivers of the same kind (e.g. mysql -> postgres).
    if (currentDriver.kind !== newDriver.kind) {
      fs.writeFileSync(path.join(ormFeatureDir, "orm.config.js"), ormConfigContent(newDriver.kind));
      this.log(`Regenerated orm.config.js (storage kind changed: ${currentDriver.kind} -> ${newDriver.kind}).`);
    }

    // Network drivers each need their own env vars (DATABASE_URL's scheme
    // differs — mysql:// vs postgres:// vs mongodb://) even when kind stays
    // "network" across the switch (e.g. mysql -> postgres), so this runs
    // regardless of the kind check above. Idempotent and additive — never
    // overwrites an existing DATABASE_URL, since it could be a real,
    // already-configured connection string (possibly prod credentials);
    // silently rewriting it would be far worse than leaving it stale.
    writeEnvVars({ cwd, label: newDriverName, vars: newDriver.env ?? [], log: (m) => this.log(m) });

    if (currentDriver.kind === "network" && newDriver.kind === "network" && (newDriver.env?.length ?? 0) > 0) {
      this.warn(
        `DATABASE_URL (and TEST_DATABASE_URL) already existed for "${currentDriverName}" and was left untouched — ` +
          `it almost certainly has the wrong scheme for "${newDriverName}" now. Update it by hand.`,
      );
    }

    // package.json: drop the old driver's package, add the new one.
    const targetPackageJsonPath = path.join(cwd, "package.json");
    const targetPackageJson = JSON.parse(fs.readFileSync(targetPackageJsonPath, "utf8")) as JsonObject;
    const dependencies = (targetPackageJson.dependencies as JsonObject) ?? {};
    delete dependencies[currentDriver.package];
    dependencies[newDriver.package] = "*";
    targetPackageJson.dependencies = dependencies;
    fs.writeFileSync(targetPackageJsonPath, JSON.stringify(targetPackageJson, null, 2) + "\n");

    this.log(`Installing ${newDriver.package}...`);
    const result = spawnSync("npm", ["install", newDriver.package], { cwd, stdio: "inherit" });
    if (result.status !== 0) {
      this.warn("Install failed — run your package manager's install command manually.");
    }

    this.log(`Switched features/orm/ from "${currentDriverName}" to "${newDriverName}".`);
    this.warn(
      `Existing data was NOT migrated from ${currentDriverName} to ${newDriverName} — that's on you. ` +
        `Models keep working unchanged (they only ever require("../driver.js")).`,
    );
  }
}
